import 'package:isar/isar.dart';

part 'word.g.dart';
// This links the generated code file created by running the build_runner command.
// Run the following command in the terminal to generate this file:
// flutter pub run build_runner build

@collection
class Word {
  // ID is automatically generated by Isar, no need to provide it manually.
  Id id = Isar.autoIncrement;
  late String englishWord;
  late String turkishWord;
  late String wordType;
  String? story;
  List<int>? imageBytes;
  // A new word is considered not learned by default, so no need to require this in the constructor.
  bool isLearned = false;
  Word({
    required this.englishWord,
    required this.turkishWord,
    required this.wordType,
    this.story,
    this.imageBytes, required bool isLearned,
  });

  @override
  String toString() {
    return 'Word(id: $id, englishWord: $englishWord, turkishWord: $turkishWord, wordType: $wordType, story: $story, imageBytes: $imageBytes, isLearned: $isLearned)';
  }
}
